#! /bin/sh
gcc -g -Wall -Werror trace.c checksum.c -lpcap -o trace

echo "testing Arp"
./trace ArpTest.pcap > mytest
diff mytest ArpTest.out
rm mytest

echo "testing IP_BAD_CHECK"
./trace IP_bad_checksum.pcap > mytest
diff mytest IP_bad_checksum.out
rm mytest

echo "testing largemix"
./trace largeMix.pcap > mytest
diff mytest largeMix.out
rm mytest

echo "testing largemix2"
./trace largeMix2.pcap > mytest
diff mytest largeMix2.out
rm mytest

echo "testing ping"
./trace PingTest.pcap > mytest
diff mytest PingTest.out
rm mytest

echo "testing smalltcp"
./trace smallTCP.pcap > mytest
diff mytest smallTCP.out
rm mytest

echo "testing tcp_bad_check"
./trace TCP_bad_checksum.pcap > mytest
diff mytest TCP_bad_checksum.out
rm mytest

echo "done"