#!/bin/bash

echo ----------------------------------------
echo Test 0010
echo ----------------------------------------
gcc -Wall -Werror -O3 CodeSetSilver.o BitUnpacker.o LZWExp.c TestExp.o SmartAlloc.c
bash TESTALL

echo ----------------------------------------
echo Test 0011
echo ----------------------------------------
gcc -Wall -Werror -O3 CodeSetSilver.o BitUnpacker.o LZWExp.c TestExp.c SmartAlloc.c
bash TESTALL

echo ----------------------------------------
echo Test 0110
echo ----------------------------------------
gcc -Wall -Werror -O3 CodeSetSilver.o BitUnpacker.c LZWExp.c TestExp.o SmartAlloc.c
bash TESTALL

echo ----------------------------------------
echo Test 0111
echo ----------------------------------------
gcc -Wall -Werror -O3 CodeSetSilver.o BitUnpacker.c LZWExp.c TestExp.c SmartAlloc.c
bash TESTALL

echo ----------------------------------------
echo Test 1010
echo ----------------------------------------
gcc -Wall -Werror -O3 CodeSet.c BitUnpacker.o LZWExp.c TestExp.o SmartAlloc.c
bash TESTALL

echo ----------------------------------------
echo Test 1011
echo ----------------------------------------
gcc -Wall -Werror -O3 CodeSet.c BitUnpacker.o LZWExp.c TestExp.c SmartAlloc.c
bash TESTALL

echo ----------------------------------------
echo Test 1110
echo ----------------------------------------
gcc -Wall -Werror -O3 CodeSet.c BitUnpacker.c LZWExp.c TestExp.o SmartAlloc.c
bash TESTALL

echo ----------------------------------------
echo Test 1111
echo ----------------------------------------
gcc -Wall -Werror -O3 CodeSet.c BitUnpacker.c LZWExp.c TestExp.c SmartAlloc.c
bash TESTALL


