#!/bin/bash
echo ------------------
echo Bronze - Test 1
echo ------------------
./a.out < tests/Bronze/test1.in > mytest1.out
diff tests/Bronze/test1.out mytest1.out
echo ------------------
echo Bronze - Test 2
echo ------------------
./a.out < tests/Bronze/test2.in > mytest2.out
diff tests/Bronze/test2.out mytest2.out
echo ------------------
echo Bronze - Test 3
echo ------------------
./a.out < tests/Bronze/test3.in > mytest3.out
diff tests/Bronze/test3.out mytest3.out
echo ------------------
echo Bronze - Test 4
echo ------------------
./a.out < tests/Bronze/test4.in > mytest4.out
diff tests/Bronze/test4.out mytest4.out
echo ------------------
echo Bronze - Test 9
echo ------------------
./a.out < tests/Bronze/test9.in > mytest9.out
diff tests/Bronze/test9.out mytest9.out
echo ------------------
echo Bronze - Test 12
echo ------------------
./a.out < tests/Bronze/test12.in > mytest12.out
diff tests/Bronze/test12.out mytest12.out
echo ------------------
echo Bronze - Test 13
echo ------------------
./a.out < tests/Bronze/test13.in > mytest13.out
diff tests/Bronze/test13.out mytest13.out